### ISSUE TITLE
Cannot find host interface on "host" for item key "APRZ-[{#SNMPVALUE}]".

### ISSUE THREAD

**Issue by maxxer** [rggassner/gassnerZabbixTemplates#1]
When I try to add the template to a host I get that error. 

Zabbix 3.4.2 freshly installed

**Comment by maxxer** [comment]
My fault, I didn't add the SNMP interface ☹️

**Comment by rggassner** [comment]
Thanks for the feedback! Let me know if you find any problem or any possibility of improvement.
Best regards
