### ISSUE TITLE
Queue issue on AP's down

### ISSUE THREAD

**Issue by axlroden** [rggassner/gassnerZabbixTemplates#2]
On sites where I have AP's down (spare/or otherwise) The queue for those sites grows like crazy. I currently have a queue size of 30k because I have roughly 60 AP's down over all my sites.

I'm guessing this is because AP's are not treated like individual hosts.

You know if its possible to discover AP's as separate hosts, instead of items on the Controller?

**Comment by rggassner** [comment]
You are right,  aps are items.  It is possible to dynamically create hosts,  but that would change completely the template. You can disable unsupported items as a workaround.
